modLoader = "javafml"
loaderVersion = "[0,)"
license = "GPL-3.0-only"
logoFile = "logo.png"

[[mods]]
modId = "legendarium"
version = "24.10.09"
displayName = "Legendary Item"
authors = "Hummel009"
description = '''This mod adds legendary artifacts from the Lord of the Rings to Minecraft.'''

[[dependencies.legendarium]]
modId = "forge"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.legendarium]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5]"
ordering = "NONE"
side = "BOTH"